#!/bin/bash
#-------------------------------------------------------------------
#
# gladec.sh
# 	USAGE:gladec.sh <path_to_file.glade>
#
# 	DESCRIPTION
#	Creates the .c and .h files with the code generated from glade.
#	Puts the code inside a global constant "const char * gtkSource"
#	and creates "const char * getGtkSource(void)" function which
#	returns the content of the constant in any part of the program.
#
#	It also creates the header file to include getGtkSource(void) in
#	each part of the program in which the constant gtkSource is required.
#
#	Don't forget to include the .c file in your makefile in order to be
#	included in the compilation process.
#
#-------------------------------------------------------------------


#-------------------------------------------------------------------
#
# .c file code generator
#
#-------------------------------------------------------------------
filename=`basename $1`
filename=${filename//\./_}.c
echo "/*" > $filename
echo " * $filename" >> $filename
echo " *" >> $filename
echo " *  Created on: `date`" >> $filename
echo " *      Author: $USER" >> $filename
echo " *		File and code generated automatically from $0" >> $filename
echo " *		Includes the XML generated by glade from $1" >> $filename
echo " */" >> $filename
echo "">> $filename

echo "/**" >> $filename
echo " * Glade GTK Window Source Code from $1" >> $filename
echo " * To include the XML generated by glade" >> $filename
echo " * 	1. Escape all the double quotes inside the XML: '\"' -> '\\\"'" >> $filename
echo " * 	2. You should end the XML with NULL" >> $filename
echo " */" >> $filename
echo "">> $filename

echo "const char * gtkSource = \"\\" >> $filename
IFS=''
while read -r line || [[ -n "$line" ]]; do
	line=${line//\"/\\\"}
    echo "$line\\" >> $filename 
done < $1
echo "\";" >> $filename
echo "">> $filename

echo "const char * getGtkSource(void)" >> $filename
echo "{" >> $filename
echo "	return gtkSource;" >> $filename
echo "}" >> $filename

#-------------------------------------------------------------------
#
# .h file code generator
#
#-------------------------------------------------------------------
filename=`basename $1`
filename=${filename//\./_}.h
echo "/*" > $filename
echo " * $filename" >> $filename
echo " *" >> $filename
echo " *  Created on: `date`" >> $filename
echo " *      Author: $USER" >> $filename
echo " *		File and code generated automatically from $0" >> $filename
echo " */" >> $filename
echo "">> $filename

defFlag=${filename//\./_}_
defFlag=`tr '[:lower:]' '[:upper:]' <<< $defFlag`
defFlag=SOURCE_$defFlag

echo "#ifndef $defFlag" >> $filename
echo "#define $defFlag" >> $filename
echo "">> $filename
echo "const char * getGtkSource(void);" >> $filename
echo "">> $filename
echo "#endif /* $defFlag */" >> $filename

